# Generated by Django 3.0.4 on 2020-03-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200311_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name_auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.Author'),
            preserve_default=False,
        ),
    ]
