# Generated by Django 3.0.4 on 2020-03-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_book_name_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name_auth',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nameauth', to='quickstart.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='namecat', to='quickstart.Category'),
            preserve_default=False,
        ),
    ]
